baseURL = 'https://stinkydoes.art/'
languageCode = 'en-us'
title = 'stinky does art'
theme = 'typo'
enableEmoji = true


[params]
homeIntroTitle = 'Art should stink!'

homeIntroContent = """
Make the art you want to see! Make it even if it sucks! Even if it downright stinks!
![Make art that sucks! Says a man with a combover and glasses](/images/art_sucks.png)
"""

# Meta description
description = "Stinky's portfolio"

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = false

paginationSize = 100

# footer
showFooter = true
footerContent = "Made with ❤ in Oakland, CA"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "zines"
url = "/zines"

[[params.menu]]
name = "about"
url = "/about"